---
title: "Heat map of expression in mini-bulks"
author: "Kevin Rue-Albrecht"
date: "06/01/2018"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
stopifnot(
  require(DESeq2),
  require(ComplexHeatmap),
  require(RColorBrewer)
)
sce.norm <- readRDS("rds/sce.minibulks.vsd.pca.rds")
outdir <- "007_out"; dir.create(outdir)
dds <- readRDS("rds/DESeq2_dds.rds")
deseq.res <- readRDS("rds/deseq.res.rds")
```

# Color maps

```{r colorRampPalette}
blackred <- colorRampPalette(c("black","brown","red","orange","yellow"))(20)
purpleblackyellow <- colorRampPalette(c("purple","black","yellow"))(10)
```

```{r}
col.time <- brewer.pal(9, "Set3")[c(2,7:8)]
col.infection <- brewer.pal(12, "Paired")[c(9,4,2)]
col.status <- brewer.pal(12, "Paired")[c(9,1,7)]
names(col.time) <- levels(sce.norm$Time)[1:3]
names(col.infection) <- levels(sce.norm$Infection)
names(col.status) <- levels(sce.norm$Status)
```


# Heat map of the `MARCH*` genes at 6h p.i.

```{r}
samples_6h <- rownames(subset(colData(sce.norm), Time == "6h"))
march_data <- rowData(sce.norm)[grep("^MARCH", rowData(sce.norm)[,"gene_name"]),]
heat_data <- assay(sce.norm, "vsd")[march_data$gene_id, samples_6h]
rownames(heat_data) <- march_data$gene_name
col_data <- colData(sce.norm)[samples_6h, c("Infection","Status")]
ha <- HeatmapAnnotation(df = col_data)
Heatmap(matrix = heat_data, top_annotation = ha)
# Heatmap(matrix = t(scale(t(heat_data))), top_annotation = ha)
# Heatmap(matrix = t(scale(t(heat_data))), top_annotation = ha, col = colors)
```

# MARCH1, CD83 and IL10 at 6h p.i.

```{r}
gene_names <- c("MARCH1","CD83","IL10")
gene_ids <- with(rowData(sce.norm), gene_id[match(gene_names, gene_name)])
heat_data <- assay(sce.norm, "vsd")[gene_ids, samples_6h]
rownames(heat_data) <- gene_names
# Heatmap(matrix = heat_data, top_annotation = ha)
Heatmap(matrix = t(scale(t(heat_data))), top_annotation = ha)
```

# MARCH1, CD83 and IL10 at 6h p.i. across time points

```{r}
sce.norm <- sce.norm[,order(sce.norm$Group)]
gene_names <- c("MARCH1","CD83","IL10")
gene_ids <- with(rowData(sce.norm), gene_id[match(gene_names, gene_name)])
heat_data <- t(scale(t(assay(sce.norm, "vsd")[gene_ids,])))
rownames(heat_data) <- gene_names
#
samples_2h <- rownames(subset(colData(sce.norm), Time == "2h"))
samples_4h <- rownames(subset(colData(sce.norm), Time == "4h"))
samples_6h <- rownames(subset(colData(sce.norm), Time == "6h"))
heat_data_2h <- heat_data[,samples_2h]
heat_data_4h <- heat_data[,samples_4h]
heat_data_6h <- heat_data[,samples_6h]
#
ha_2 <- HeatmapAnnotation(
  df = colData(sce.norm)[samples_2h, c("Infection","Status")],
  col = list(Infection = col.infection, Status = col.status)
)
ha_4 <- HeatmapAnnotation(
  df = colData(sce.norm)[samples_4h, c("Infection","Status")],
  col = list(Infection = col.infection, Status = col.status)
)
ha_6 <- HeatmapAnnotation(
  df = colData(sce.norm)[samples_6h, c("Infection","Status")],
  col = list(Infection = col.infection, Status = col.status)
)
#
ht_2 <- Heatmap(
  matrix = heat_data_2h, top_annotation = ha_2,
  cluster_rows = FALSE, cluster_columns = FALSE,
  col = purpleblackyellow,
  show_row_names = TRUE, show_column_names = FALSE,
  row_names_side = "left"
)
ht_4 <- Heatmap(
  matrix = heat_data_4h, top_annotation = ha_4,
  cluster_rows = FALSE, cluster_columns = FALSE,
  col = purpleblackyellow,
  show_row_names = FALSE, show_column_names = FALSE,
  show_heatmap_legend = FALSE
)
ht_6 <- Heatmap(
  matrix = heat_data_6h, top_annotation = ha_6,
  cluster_rows = FALSE, cluster_columns = FALSE,
  col = purpleblackyellow,
  show_row_names = FALSE, show_column_names = FALSE,
  show_heatmap_legend = FALSE
)
# pdf(file.path(outdir, "heatmap_MARCH1_CD83_IL10_all_time_bluewhitered.pdf"), width = 12, height = 3)
pdf(file.path(outdir, "heatmap_MARCH1_CD83_IL10_all_time_purpleblackyellow.pdf"), width = 12, height = 3)
draw(ht_2 + ht_4 + ht_6)
dev.off()
```

# Genes DE in STM-D23580 Violet +/Exposed at any time point

```{r}
names(deseq.res)
tmp_contrasts <- grep("STM-D23580_Violet \\+-.*Exposed", names(deseq.res), value = TRUE)
tmp_DEgeneList <- lapply(tmp_contrasts, function(x){
  rownames(subset(deseq.res[[x]], padj < 0.05))
})
tmp_DEgenes <- unique(unlist(tmp_DEgeneList))
```
