---
title: "Scan differentially expressed"
author: "Kevin Rue-Albrecht"
date: "28/12/2017"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
sce.norm <- readRDS("rds/sce.norm.rds")
scde.res <- readRDS("rds/scde_group.rds")
addGeneName <- function(x){
  x <- cbind(
    gene_name = with(rowData(sce.norm), gene_name[match(x$gene_id, gene_id)]),
    x
  )
  return(x)
}
convert.z.score <- function(x, one.sided = NULL) {
  z <- x$Z
  if(is.null(one.sided)) {
    pval = pnorm(-abs(z));
    pval = 2 * pval
  } else if(one.sided=="-") {
    pval = pnorm(z);
  } else {
    pval = pnorm(-z);
  }
    x <- cbind(
      x,
      p.value = pval
  )
  return(x);
}   
```

```{r fullTableDirect}
fullTableDirect <- do.call("rbind", scde.res)
```

```{r format_fullTableDirect}
tmpSplit <- strsplit(rownames(fullTableDirect), ".", fixed = TRUE)
tmpSplit <- data.frame(do.call("rbind", tmpSplit))
colnames(tmpSplit) <- c("contrast", "gene_id")
fullTableDirect <- cbind(tmpSplit, fullTableDirect)
rownames(fullTableDirect) <- NULL
```

```{r append_fullTableDirect}
fullTableDirect <- addGeneName(fullTableDirect)
fullTableDirect <- convert.z.score(fullTableDirect)
```

```{r View_fullTableDirect}
# View(subset(fullTableDirect, gene_name == "CTSL" & p.value < 0.01))
# View(subset(fullTableDirect, gene_name == "CTSS" & p.value < 0.01))
# View(subset(fullTableDirect, gene_name == "CTSD" & p.value < 0.01))
# View(subset(fullTableDirect, gene_name == "CYBB" & p.value < 0.01))
# View(subset(fullTableDirect, gene_name == "CEBPA" & p.value < 0.01))
# View(subset(fullTableDirect, gene_name == "CEBPB" & p.value < 0.01))
# View(subset(fullTableDirect, gene_name == "IL10RA" & p.value < 0.01))
# View(subset(fullTableDirect, gene_name == "IL10RB" & p.value < 0.01))
# View(subset(fullTableDirect, gene_name == "TYK2" & p.value < 0.01))
# View(subset(fullTableDirect, gene_name == "JAK1" & p.value < 0.01))
# View(subset(fullTableDirect, gene_name == "JAK1"))
# View(subset(fullTableDirect, gene_name == "STAT3" & p.value < 0.01))
View(subset(fullTableDirect, gene_name == "SYK" & p.value < 0.01))
View(subset(fullTableDirect, gene_name == "RAF1" & p.value < 0.01))
View(subset(fullTableDirect, gene_name == "SOCS1" & p.value < 0.01))
View(subset(fullTableDirect, gene_name == "SOCS3" & p.value < 0.01))
View(subset(fullTableDirect, gene_name == "BCL3" & p.value < 0.01))
View(subset(fullTableDirect, gene_name == "NFIL3" & p.value < 0.01))
# grep("IL10R", fullTableDirect$gene_name, value = TRUE)
```

# DE genes matching conditions

## DE @ 6h Violet + STM-D23580/STM-LT2 & 6h STM-D23580 Violet +/Uninfected

Genes that are:

* DE in contrast: `6h_STM-D23580_Violet +-6h_STM-LT2_Violet +`
* DE in contrast: `6h_STM-D23580_Violet +-6h_Mock_Uninfected`

```{r query_1}
contrast.name <- "6h_STM-D23580_Violet +-6h_Mock_Uninfected"
de.id <- rownames(scde.res[[contrast.name]])[with(
  convert.z.score(scde.res[[contrast.name]]),
  which(p.value < 0.01 & mle < 0)
)]
contrast.name <- "6h_STM-D23580_Violet +-6h_STM-LT2_Violet +"
de.id <- intersect(
  de.id,
  rownames(scde.res[[contrast.name]])[with(
    convert.z.score(scde.res[[contrast.name]]),
    which(p.value < 0.01 & mle < 0)
  )]
)
de.info <- data.frame(
  gene_id = de.id,
  gene_name = with(rowData(sce.norm), gene_name[match(de.id, gene_id)])
)
```

```{r query_2}
contrast.name <- "6h_STM-D23580_Violet +-6h_Mock_Uninfected"
de.id <- rownames(scde.res[[contrast.name]])[with(
  convert.z.score(scde.res[[contrast.name]]),
  which(p.value < 0.01 & mle < 0)
)]
contrast.name <- "6h_STM-LT2_Violet +-6h_Mock_Uninfected"
de.id <- intersect(
  de.id,
  rownames(scde.res[[contrast.name]])[with(
    convert.z.score(scde.res[[contrast.name]]),
    which(p.value > 0.01)
  )]
)
de.info <- data.frame(
  gene_id = de.id,
  gene_name = with(rowData(sce.norm), gene_name[match(de.id, gene_id)])
)
```


