---
title: "Heat map of genes DE in STM23580 violet/exposed"
author: "Kevin Rue-Albrecht"
date: "27/01/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
stopifnot(
    require(scater),
    require(scran),
    require(ggplot2),
    require(SummarizedExperiment),
    require(RColorBrewer),
    require(circlize),
    require(ComplexHeatmap)
)
sce.norm <- readRDS("rds/sce.norm.rds")
sce.norm <- sce.norm[,order(sce.norm$Group)]
sce.endo <- sce.norm[!isSpike(sce.norm, "ERCC"),]
col.time <- brewer.pal(9, "Set3")[c(2,7:8)]
col.infection <- brewer.pal(12, "Paired")[c(9,4,2)]
col.status <- brewer.pal(12, "Paired")[c(9,1,7)]
names(col.time) <- levels(sce.endo$Time)[1:3]
names(col.infection) <- levels(sce.endo$Infection)
names(col.status) <- levels(sce.endo$Status)
outdir <- "_009b_heatmap_out"; dir.create(outdir, showWarnings = FALSE)
scde.res <- readRDS("rds/scde_group.rds")
convert.z.score <- function(x, one.sided = NULL) {
    z <- x$Z
    if(is.null(one.sided)) {
        pval = pnorm(-abs(z));
        pval = 2 * pval
    } else if(one.sided=="-") {
        pval = pnorm(z);
    } else {
        pval = pnorm(-z);
    }
    x <- cbind(
        x,
        p.value = pval
    )
    return(x);
}
addGeneName <- function(x){
    x <- cbind(
        gene_name = with(rowData(sce.endo), gene_name[match(rownames(x), gene_id)]),
        x
    )
    return(x)
}
```

# Color maps

## Colors

```{r}
bluered <- colorRamp2(
    breaks = seq(-3, 3, length.out = 9),
    colors = rev(brewer.pal(9, "RdBu")))
```

# DE genes between infected STM-D23580 and STM-LT2

## 2h

### blue-white-red capped at 3 standard deviations

```{r}
timepoint <- "2h"
names(scde.res)
tmp_DEgenes <- rownames(subset(
    convert.z.score(scde.res[[sprintf(
        "%s_STM-D23580_Infected-%s_STM-LT2_Infected", timepoint, timepoint)
    ]]),
    p.value < 0.01)
)
#
samplesInfected <- rownames(
    subset(colData(sce.endo), Time == timepoint & Status == "Infected"))
samplesInfected.lt2 <- rownames(subset(
    colData(sce.endo),
    Time == timepoint & Status == "Infected" & Infection == "STM-LT2"))
samplesInfected.d23 <- rownames(subset(
    colData(sce.endo),
    Time == timepoint & Status == "Infected" & Infection == "STM-D23580"))
#
heatmapData <- assay(sce.endo, "logcounts")[tmp_DEgenes, samplesInfected]
#
heatmapData <- t(scale(t(heatmapData)))
#
row_clust <- hclust(dist(heatmapData[tmp_DEgenes,]))
#
heatmapData.lt2 <- heatmapData[, samplesInfected.lt2]
heatmapData.d23 <- heatmapData[, samplesInfected.d23]
#
ha.lt2 <- HeatmapAnnotation(
    df = colData(sce.endo)[samplesInfected.lt2, c("Infection"), drop = FALSE],
    col = list(Infection = col.infection)
)
ha.d23 <- HeatmapAnnotation(
    df = colData(sce.endo)[samplesInfected.d23, c("Infection"), drop = FALSE],
    col = list(Infection = col.infection)
)
#
ht.lt2 <- Heatmap(
    matrix = heatmapData.lt2, top_annotation = ha.lt2,
    cluster_rows = row_clust,
    cluster_columns = TRUE,
    col = bluered,
    show_row_names = FALSE,
    show_column_names = FALSE, width = unit(3, "in")
)
ht.d23 <- Heatmap(
    matrix = heatmapData.d23, top_annotation = ha.d23,
    cluster_rows = row_clust,
    cluster_columns = TRUE,
    col = bluered,
    show_row_names = FALSE,
    show_column_names = FALSE,
    row_names_side = "right", width = unit(3, "in")
)
#
pdf(file.path(outdir, sprintf("DE_violet_%s.pdf", timepoint)), width = 9, height = 7)
draw(ht.lt2 + ht.d23)
dev.off()
```

With gene labels

```{r}
GOIs <- c("CHST13", "MUT", "ASB6", "DCUN1D2", "MALAT1", "KIFC2", "DUSP2", "TRIM13", "SNCA")
stopifnot(all(GOIs %in% rowData(sce.endo)[["gene_name"]]))
GOIs <- data.frame(
    gene_name = GOIs,
    gene_id = with(rowData(sce.endo), gene_id[match(GOIs, gene_name)]),
    stringsAsFactors = FALSE
)
ra <- rowAnnotation(
  link = row_anno_link(
    at = match(GOIs$gene_id, rownames(heatmapData)),
    labels = GOIs$gene_name,
    labels_gp = gpar(cex=2),
    link_width = unit(0.5, "inches")
  ), width = unit(2.5, "in")
)
pdf(file.path(outdir, sprintf("DE_violet_%s_label.pdf", timepoint)), width = 12, height = 13)
draw(ht.lt2 + ht.d23 + ra)
dev.off()
```


## 4h

### blue-white-red capped at 3 standard deviations

```{r}
timepoint <- "4h"
names(scde.res)
tmp_DEgenes <- rownames(subset(
    convert.z.score(scde.res[[sprintf(
        "%s_STM-D23580_Infected-%s_STM-LT2_Infected", timepoint, timepoint)
    ]]),
    p.value < 0.01)
)
#
samplesInfected <- rownames(
    subset(colData(sce.endo), Time == timepoint & Status == "Infected"))
samplesInfected.lt2 <- rownames(subset(
    colData(sce.endo),
    Time == timepoint & Status == "Infected" & Infection == "STM-LT2"))
samplesInfected.d23 <- rownames(subset(
    colData(sce.endo),
    Time == timepoint & Status == "Infected" & Infection == "STM-D23580"))
#
heatmapData <- assay(sce.endo, "logcounts")[tmp_DEgenes, samplesInfected]
#
heatmapData <- t(scale(t(heatmapData)))
#
row_clust <- hclust(dist(heatmapData[tmp_DEgenes,]))
#
heatmapData.lt2 <- heatmapData[, samplesInfected.lt2]
heatmapData.d23 <- heatmapData[, samplesInfected.d23]
#
ha.lt2 <- HeatmapAnnotation(
    df = colData(sce.endo)[samplesInfected.lt2, c("Infection"), drop = FALSE],
    col = list(Infection = col.infection)
)
ha.d23 <- HeatmapAnnotation(
    df = colData(sce.endo)[samplesInfected.d23, c("Infection"), drop = FALSE],
    col = list(Infection = col.infection)
)
#
ht.lt2 <- Heatmap(
    matrix = heatmapData.lt2, top_annotation = ha.lt2,
    cluster_rows = row_clust,
    cluster_columns = TRUE,
    col = bluered,
    show_row_names = FALSE,
    show_column_names = FALSE, width = unit(3, "in")
)
ht.d23 <- Heatmap(
    matrix = heatmapData.d23, top_annotation = ha.d23,
    cluster_rows = row_clust,
    cluster_columns = TRUE,
    col = bluered,
    show_row_names = FALSE,
    show_column_names = FALSE,
    row_names_side = "right", width = unit(3, "in")
)
#
pdf(file.path(outdir, sprintf("DE_violet_%s.pdf", timepoint)), width = 9, height = 7)
draw(ht.lt2 + ht.d23)
dev.off()
```

With gene labels

```{r}
GOIs <- c("MYLIP", "GORASP1", "RIPK3", "KLHL2", "HEBP2", "APOBEC3A", "BCL3", "CCL22", "IFT57", "COPS7B", "CASP3", "STXBP1", "VPS25")
stopifnot(all(GOIs %in% rowData(sce.endo)[["gene_name"]]))
GOIs <- data.frame(
    gene_name = GOIs,
    gene_id = with(rowData(sce.endo), gene_id[match(GOIs, gene_name)]),
    stringsAsFactors = FALSE
)
ra <- rowAnnotation(
  link = row_anno_link(
    at = match(GOIs$gene_id, rownames(heatmapData)),
    labels = GOIs$gene_name,
    labels_gp = gpar(cex=2),
    link_width = unit(0.5, "inches")
  ), width = unit(2.5, "in")
)
pdf(file.path(outdir, sprintf("DE_violet_%s_label.pdf", timepoint)), width = 12, height = 13)
draw(ht.lt2 + ht.d23 + ra)
dev.off()
```

## 6h

### blue-white-red capped at 3 standard deviations

```{r}
timepoint <- "6h"
names(scde.res)
tmp_DEgenes <- rownames(subset(
    convert.z.score(scde.res[[sprintf(
        "%s_STM-D23580_Infected-%s_STM-LT2_Infected", timepoint, timepoint)
    ]]),
    p.value < 0.01)
)
#
samplesInfected <- rownames(
    subset(colData(sce.endo), Time == timepoint & Status == "Infected"))
samplesInfected.lt2 <- rownames(subset(
    colData(sce.endo),
    Time == timepoint & Status == "Infected" & Infection == "STM-LT2"))
samplesInfected.d23 <- rownames(subset(
    colData(sce.endo),
    Time == timepoint & Status == "Infected" & Infection == "STM-D23580"))
#
heatmapData <- assay(sce.endo, "logcounts")[tmp_DEgenes, samplesInfected]
#
heatmapData <- t(scale(t(heatmapData)))
#
row_clust <- hclust(dist(heatmapData[tmp_DEgenes,]))
#
heatmapData.lt2 <- heatmapData[, samplesInfected.lt2]
heatmapData.d23 <- heatmapData[, samplesInfected.d23]
#
ha.lt2 <- HeatmapAnnotation(
    df = colData(sce.endo)[samplesInfected.lt2, c("Infection"), drop = FALSE],
    col = list(Infection = col.infection)
)
ha.d23 <- HeatmapAnnotation(
    df = colData(sce.endo)[samplesInfected.d23, c("Infection"), drop = FALSE],
    col = list(Infection = col.infection)
)
#
ht.lt2 <- Heatmap(
    matrix = heatmapData.lt2, top_annotation = ha.lt2,
    cluster_rows = row_clust,
    cluster_columns = TRUE,
    col = bluered,
    show_row_names = FALSE,
    show_column_names = FALSE, width = unit(3, "in")
)
ht.d23 <- Heatmap(
    matrix = heatmapData.d23, top_annotation = ha.d23,
    cluster_rows = row_clust,
    cluster_columns = TRUE,
    col = bluered,
    show_row_names = FALSE,
    show_column_names = FALSE,
    row_names_side = "right", width = unit(3, "in")
)
#
pdf(file.path(outdir, sprintf("DE_violet_%s.pdf", timepoint)), width = 9, height = 7)
draw(ht.lt2 + ht.d23)
dev.off()
```

With gene labels

```{r}
GOIs <- c("MARCH1", "CLECL1", "NIT1", "NIT2", "LRR1", "VPS8", "TXNRD1", "TFRC", "USP1", "TRIAP1", "CLASP1", "RNF139", "MVB12A", "CLEC16A", "BLOC1S3", "USPL1", "DNAJC13")
stopifnot(all(GOIs %in% rowData(sce.endo)[["gene_name"]]))
GOIs <- data.frame(
    gene_name = GOIs,
    gene_id = with(rowData(sce.endo), gene_id[match(GOIs, gene_name)]),
    stringsAsFactors = FALSE
)
ra <- rowAnnotation(
  link = row_anno_link(
    at = match(GOIs$gene_id, rownames(heatmapData)),
    labels = GOIs$gene_name,
    labels_gp = gpar(cex=2),
    link_width = unit(0.5, "inches")
  ), width = unit(2.5, "in")
)
pdf(file.path(outdir, sprintf("DE_violet_%s_label.pdf", timepoint)), width = 12, height = 13)
draw(ht.lt2 + ht.d23 + ra)
dev.off()
```
