---
title: "Untitled"
author: "Kevin Rue-Albrecht"
date: "04/02/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

---
title: "Heat map of genes DE in STM23580 violet/exposed"
author: "Kevin Rue-Albrecht"
date: "27/01/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE)
stopifnot(
  require(scater),
  require(scran),
  require(ggplot2), require(ggrepel),
  require(SummarizedExperiment),
  require(RColorBrewer),
  require(circlize),
  require(ComplexHeatmap)
)
sce.norm <- readRDS("rds/sce.norm.rds")
sce.norm <- sce.norm[,order(sce.norm$Group)]
sce.endo <- sce.norm[!isSpike(sce.norm, "ERCC"),]
col.time <- brewer.pal(9, "Set3")[c(2,7:8)]
col.infection <- brewer.pal(12, "Paired")[c(9,4,2)]
col.status <- brewer.pal(12, "Paired")[c(9,1,7)]
names(col.time) <- levels(sce.endo$Time)[1:3]
names(col.infection) <- levels(sce.endo$Infection)
names(col.status) <- levels(sce.endo$Status)
outdir <- "_010_violins_infected_out"; dir.create(outdir, showWarnings = FALSE)
scde.res <- readRDS("rds/scde_group.rds")
convert.z.score <- function(x, one.sided = NULL) {
  z <- x$Z
  if(is.null(one.sided)) {
    pval = pnorm(-abs(z));
    pval = 2 * pval
  } else if(one.sided=="-") {
    pval = pnorm(z);
  } else {
    pval = pnorm(-z);
  }
    x <- cbind(
      x,
      p.value = pval
  )
  return(x);
}
addGeneName <- function(x){
  x <- cbind(
    gene_name = with(rowData(sce.endo), gene_name[match(rownames(x), gene_id)]),
    x
  )
  return(x)
}
sig.levels <- c(0.05, 0.01)
volcano.sig <- data.frame(
  p.value = sig.levels,
  level = as.character(sig.levels)
)
sig_colors <- c("grey", "red")
names(sig_colors) <- c(FALSE, TRUE)
sig_alpha <- c(0.2, 0.8)
names(sig_alpha) <- c(FALSE, TRUE)
sig_size <- c(0.2, 0.6)
names(sig_size) <- c(FALSE, TRUE)
```

# Volcanos

## 2h

```{r volcano_2h_infected.pdf}
names(scde.res)
contrastName <- "2h_STM-D23580_Infected-2h_STM-LT2_Infected"
res_table <- scde.res[[contrastName]]
res_table <- addGeneName(convert.z.score(res_table))
z.range <- max(abs(res_table$Z)) * c(-1,1)
p.range <- rev(-log10(range(res_table$p.value)))
head(res_table)
gg <- ggplot(res_table, aes(Z, -log10(p.value))) +
  geom_point(aes(Z, -log10(p.value), colour = p.value < 0.01), size = 0.5) +
  geom_hline(yintercept = -log10(0.01), linetype = "dashed", alpha = 0.25) +
  # geom_text_repel(
  #   aes(Z, -log10(p.value), label = gene_name), geneData,
  #   size = 2, min.segment.length = unit(0, "mm"), alpha = 0.75,
  #   nudge_x = ifelse(geneData$Z > 0, 1, -1), nudge_y = 0, segment.size = 0.2,
  #   fontface = "bold"
  # ) +
  scale_x_continuous(limits = z.range) +
  scale_y_continuous(limits = p.range) +
  theme_bw() +
  labs(
    title = "2h Infected", subtitle = "STM-D23580 / STM-LT2",
    y = expression(-log[10]*" ("*italic(P)*"-value)")
  ); gg
ggsave(file.path(outdir, "volcano_2h_infected.pdf"), gg, height=5, width=6.5)
```

```{r mean_2h_infected.pdf}
conditions <- c("2h_STM-D23580_Infected","2h_STM-LT2_Infected")
ggdata <- data.frame(
  y_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[1]]),
  x_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[2]]),
  DE = rownames(sce.endo) %in% row.names(res_table)[res_table$p.value < 0.01]
)
axes_range <- c(0, max(c(ggdata$y_logcounts, ggdata$x_logcounts)))
gg <- ggplot(ggdata, aes(x_logcounts, y_logcounts)) +
  geom_point(aes(colour = DE, alpha = DE, size = DE)) +
  scale_colour_manual(values = sig_colors) +
  scale_alpha_manual(values = sig_alpha) +
  scale_size_manual(values = sig_size) +
  scale_y_continuous(limits = axes_range) +
  scale_x_continuous(limits = axes_range) +
  labs(
    title = "2h", subtitle = "STM-D23580 / STM-LT2",
    y = "STM-D23580", x = "STM-LT2"
  ) +
  guides(colour="none", size="none", alpha="none") +
  coord_fixed() +
  theme_bw() +
  theme(panel.grid.minor = element_blank()); gg
ggsave(file.path(outdir, "mean_2h_infected.pdf"), gg, height=5, width=6.5)
```

```{r mean_2h_infected_label.pdf}
conditions <- c("2h_STM-D23580_Infected","2h_STM-LT2_Infected")
ggdata <- data.frame(
  y_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[1]]),
  x_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[2]]),
  DE = rownames(sce.endo) %in% row.names(res_table)[res_table$p.value < 0.01],
  gene_name = rowData(sce.endo)[,"gene_name"]
)
ggdata$productMLE <- with(ggdata, y_logcounts * x_logcounts)
ggdata <- ggdata[order(ggdata$productMLE, decreasing = TRUE),]
axes_range <- c(0, max(c(ggdata$y_logcounts, ggdata$x_logcounts)))
gg <- ggplot(ggdata, aes(x_logcounts, y_logcounts)) +
  geom_point(aes(colour = DE, alpha = DE, size = DE)) +
  geom_text_repel(aes(label = gene_name), head(subset(ggdata, DE), 6)) +
  scale_colour_manual(values = sig_colors) +
  scale_alpha_manual(values = sig_alpha) +
  scale_size_manual(values = sig_size) +
  scale_y_continuous(limits = axes_range) +
  scale_x_continuous(limits = axes_range) +
  labs(
    title = "2h", subtitle = "STM-D23580 / STM-LT2",
    y = "STM-D23580", x = "STM-LT2"
  ) +
  guides(colour="none", size="none", alpha="none") +
  coord_fixed() +
  theme_bw() +
  theme(panel.grid.minor = element_blank()); gg
ggsave(file.path(outdir, "mean_2h_infected_label.pdf"), gg, height=5, width=6.5)
```

```{r mean_2h_infected_label_curated.pdf}
conditions <- c("2h_STM-D23580_Infected","2h_STM-LT2_Infected")
ggdata <- data.frame(
  y_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[1]]),
  x_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[2]]),
  DE = rownames(sce.endo) %in% row.names(res_table)[res_table$p.value < 0.01],
  gene_name = rowData(sce.endo)[,"gene_name"]
)
ggdata$Curated <- as.character(ggdata$gene_name) %in% c(
  "CHST13","DUSP2","LRRC23","KIFC2","MALAT1","SLC25A17"
)
axes_range <- c(0, max(c(ggdata$y_logcounts, ggdata$x_logcounts)))
gg <- ggplot(ggdata, aes(x_logcounts, y_logcounts)) +
  geom_point(aes(colour = DE, alpha = DE, size = DE)) +
  geom_text_repel(
    aes(label = gene_name),
    subset(ggdata, Curated), min.segment.length = unit(0,"lines")) +
  scale_colour_manual(values = sig_colors) +
  scale_alpha_manual(values = sig_alpha) +
  scale_size_manual(values = sig_size) +
  scale_y_continuous(limits = axes_range) +
  scale_x_continuous(limits = axes_range) +
  labs(
    title = "2h", subtitle = "STM-D23580 / STM-LT2",
    y = "STM-D23580", x = "STM-LT2"
  ) +
  guides(colour="none", size="none", alpha="none") +
  coord_fixed() +
  theme_bw() +
  theme(panel.grid.minor = element_blank()); gg
ggsave(file.path(outdir, "mean_2h_infected_label_curated.pdf"), gg, height=5, width=6.5)
```

## 4h

```{r volcano_4h_infected.pdf}
names(scde.res)
contrastName <- "4h_STM-D23580_Infected-4h_STM-LT2_Infected"
res_table <- scde.res[[contrastName]]
res_table <- addGeneName(convert.z.score(res_table))
z.range <- max(abs(res_table$Z)) * c(-1,1)
p.range <- rev(-log10(range(res_table$p.value)))
head(res_table)
gg <- ggplot(res_table, aes(Z, -log10(p.value))) +
  geom_point(aes(Z, -log10(p.value), colour = p.value < 0.01), size = 0.5) +
  geom_hline(yintercept = -log10(0.01), linetype = "dashed", alpha = 0.25) +
  # geom_text_repel(
  #   aes(Z, -log10(p.value), label = gene_name), geneData,
  #   size = 2, min.segment.length = unit(0, "mm"), alpha = 0.75,
  #   nudge_x = ifelse(geneData$Z > 0, 1, -1), nudge_y = 0, segment.size = 0.2,
  #   fontface = "bold"
  # ) +
  scale_x_continuous(limits = z.range) +
  scale_y_continuous(limits = p.range) +
  theme_bw() +
  labs(
    title = "4h Infected", subtitle = "STM-D23580 / STM-LT2",
    y = expression(-log[10]*" ("*italic(P)*"-value)")
  )
ggsave(file.path(outdir, "volcano_4h_infected.pdf"), gg, height=5, width=6.5)
```

```{r mean_4h_infected.pdf}
conditions <- c("4h_STM-D23580_Infected","4h_STM-LT2_Infected")
ggdata <- data.frame(
  y_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[1]]),
  x_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[2]]),
  DE = rownames(sce.endo) %in% row.names(res_table)[res_table$p.value < 0.01]
)
axes_range <- c(0, max(c(ggdata$y_logcounts, ggdata$x_logcounts)))
gg <- ggplot(ggdata, aes(x_logcounts, y_logcounts)) +
  geom_point(aes(colour = DE, alpha = DE, size = DE)) +
  scale_colour_manual(values = sig_colors) +
  scale_alpha_manual(values = sig_alpha) +
  scale_size_manual(values = sig_size) +
  scale_y_continuous(limits = axes_range) +
  scale_x_continuous(limits = axes_range) +
  labs(
    title = "4h", subtitle = "STM-D23580 / STM-LT2",
    y = "STM-D23580", x = "STM-LT2"
  ) +
  guides(colour="none", size="none", alpha="none") +
  coord_fixed() +
  theme_bw() +
  theme(panel.grid.minor = element_blank()); gg
ggsave(file.path(outdir, "mean_4h_infected.pdf"), gg, height=5, width=6.5)
```

```{r mean_4h_infected_label.pdf}
conditions <- c("4h_STM-D23580_Infected","4h_STM-LT2_Infected")
ggdata <- data.frame(
  y_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[1]]),
  x_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[2]]),
  DE = rownames(sce.endo) %in% row.names(res_table)[res_table$p.value < 0.01],
  gene_name = rowData(sce.endo)[,"gene_name"]
)
ggdata$productMLE <- with(ggdata, y_logcounts * x_logcounts)
ggdata <- ggdata[order(ggdata$productMLE, decreasing = TRUE),]
axes_range <- c(0, max(c(ggdata$y_logcounts, ggdata$x_logcounts)))
gg <- ggplot(ggdata, aes(x_logcounts, y_logcounts)) +
  geom_point(aes(colour = DE, alpha = DE, size = DE)) +
  geom_text_repel(aes(label = gene_name), head(subset(ggdata, DE), 8)) +
  scale_colour_manual(values = sig_colors) +
  scale_alpha_manual(values = sig_alpha) +
  scale_size_manual(values = sig_size) +
  scale_y_continuous(limits = axes_range) +
  scale_x_continuous(limits = axes_range) +
  labs(
    title = "4h", subtitle = "STM-D23580 / STM-LT2",
    y = "STM-D23580", x = "STM-LT2"
  ) +
  guides(colour="none", size="none", alpha="none") +
  coord_fixed() +
  theme_bw() +
  theme(panel.grid.minor = element_blank()); gg
ggsave(file.path(outdir, "mean_4h_infected_label.pdf"), gg, height=5, width=6.5)
```

```{r mean_4h_infected_label_curated.pdf}
conditions <- c("4h_STM-D23580_Infected","4h_STM-LT2_Infected")
ggdata <- data.frame(
  y_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[1]]),
  x_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[2]]),
  DE = rownames(sce.endo) %in% row.names(res_table)[res_table$p.value < 0.01],
  gene_name = rowData(sce.endo)[,"gene_name"]
)
ggdata$Curated <- as.character(ggdata$gene_name) %in% c(
  "IFT57","CH25H","BCL3","RIPK3","SLC47A1","DUSP6","CCL22","APOBEC3A"
)
axes_range <- c(0, max(c(ggdata$y_logcounts, ggdata$x_logcounts)))
gg <- ggplot(ggdata, aes(x_logcounts, y_logcounts)) +
  geom_point(aes(colour = DE, alpha = DE, size = DE)) +
  geom_text_repel(
    aes(label = gene_name),
    subset(ggdata, Curated), min.segment.length = unit(0,"lines")) +
  scale_colour_manual(values = sig_colors) +
  scale_alpha_manual(values = sig_alpha) +
  scale_size_manual(values = sig_size) +
  scale_y_continuous(limits = axes_range) +
  scale_x_continuous(limits = axes_range) +
  labs(
    title = "4h", subtitle = "STM-D23580 / STM-LT2",
    y = "STM-D23580", x = "STM-LT2"
  ) +
  guides(colour="none", size="none", alpha="none") +
  coord_fixed() +
  theme_bw() +
  theme(panel.grid.minor = element_blank()); gg
ggsave(file.path(outdir, "mean_4h_infected_label_curated.pdf"), gg, height=5, width=6.5)
```


## 6h

```{r volcano_6h_infected.pdf}
names(scde.res)
contrastName <- "6h_STM-D23580_Infected-6h_STM-LT2_Infected"
res_table <- scde.res[[contrastName]]
res_table <- addGeneName(convert.z.score(res_table))
z.range <- max(abs(res_table$Z)) * c(-1,1)
p.range <- rev(-log10(range(res_table$p.value)))
head(res_table)
gg <- ggplot(res_table, aes(Z, -log10(p.value))) +
  geom_point(aes(Z, -log10(p.value), colour = p.value < 0.01), size = 0.5) +
  geom_hline(yintercept = -log10(0.01), linetype = "dashed", alpha = 0.25) +
  # geom_text_repel(
  #   aes(Z, -log10(p.value), label = gene_name), geneData,
  #   size = 2, min.segment.length = unit(0, "mm"), alpha = 0.75,
  #   nudge_x = ifelse(geneData$Z > 0, 1, -1), nudge_y = 0, segment.size = 0.2,
  #   fontface = "bold"
  # ) +
  scale_x_continuous(limits = z.range) +
  scale_y_continuous(limits = p.range) +
  theme_bw() +
  labs(
    title = "6h Infected", subtitle = "STM-D23580 / STM-LT2",
    y = expression(-log[10]*" ("*italic(P)*"-value)")
  )
ggsave(file.path(outdir, "volcano_6h_infected.pdf"), gg, height=5, width=6.5)
```

```{r mean_6h_infected.pdf}
conditions <- c("6h_STM-D23580_Infected","6h_STM-LT2_Infected")
ggdata <- data.frame(
  y_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[1]]),
  x_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[2]]),
  DE = rownames(sce.endo) %in% row.names(res_table)[res_table$p.value < 0.01]
)
axes_range <- c(0, max(c(ggdata$y_logcounts, ggdata$x_logcounts)))
gg <- ggplot(ggdata, aes(x_logcounts, y_logcounts)) +
  geom_point(aes(colour = DE, alpha = DE, size = DE)) +
  scale_colour_manual(values = sig_colors) +
  scale_alpha_manual(values = sig_alpha) +
  scale_size_manual(values = sig_size) +
  scale_y_continuous(limits = axes_range) +
  scale_x_continuous(limits = axes_range) +
  labs(
    title = "6h", subtitle = "STM-D23580 / STM-LT2",
    y = "STM-D23580", x = "STM-LT2"
  ) +
  guides(colour="none", size="none", alpha="none") +
  coord_fixed() +
  theme_bw() +
  theme(panel.grid.minor = element_blank()); gg
ggsave(file.path(outdir, "mean_6h_infected.pdf"), gg, height=5, width=6.5)
```

```{r mean_6h_infected_label.pdf}
conditions <- c("6h_STM-D23580_Infected","6h_STM-LT2_Infected")
ggdata <- data.frame(
  y_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[1]]),
  x_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[2]]),
  DE = rownames(sce.endo) %in% row.names(res_table)[res_table$p.value < 0.01],
  gene_name = rowData(sce.endo)[,"gene_name"]
)
ggdata$productMLE <- with(ggdata, y_logcounts * x_logcounts)
ggdata <- ggdata[order(ggdata$productMLE, decreasing = TRUE),]
axes_range <- c(0, max(c(ggdata$y_logcounts, ggdata$x_logcounts)))
gg <- ggplot(ggdata, aes(x_logcounts, y_logcounts)) +
  geom_point(aes(colour = DE, alpha = DE, size = DE)) +
  geom_text_repel(aes(label = gene_name), head(subset(ggdata, DE), 8)) +
  scale_colour_manual(values = sig_colors) +
  scale_alpha_manual(values = sig_alpha) +
  scale_size_manual(values = sig_size) +
  scale_y_continuous(limits = axes_range) +
  scale_x_continuous(limits = axes_range) +
  labs(
    title = "6h", subtitle = "STM-D23580 / STM-LT2",
    y = "STM-D23580", x = "STM-LT2"
  ) +
  guides(colour="none", size="none", alpha="none") +
  coord_fixed() +
  theme_bw() +
  theme(panel.grid.minor = element_blank()); gg
ggsave(file.path(outdir, "mean_6h_infected_label.pdf"), gg, height=5, width=6.5)
```

```{r mean_6h_infected_label_curated.pdf}
conditions <- c("6h_STM-D23580_Infected","6h_STM-LT2_Infected")
ggdata <- data.frame(
  y_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[1]]),
  x_logcounts = rowMeans(assay(sce.endo, "logcounts")[,sce.endo$Group == conditions[2]]),
  DE = rownames(sce.endo) %in% row.names(res_table)[res_table$p.value < 0.01],
  gene_name = rowData(sce.endo)[,"gene_name"]
)
ggdata$Curated <- as.character(ggdata$gene_name) %in% c(
  "CLEC16A","MARCH1","BLOC1S3","CLECL1","NIT1","NIT2","TFRC"
)
axes_range <- c(0, max(c(ggdata$y_logcounts, ggdata$x_logcounts)))
gg <- ggplot(ggdata, aes(x_logcounts, y_logcounts)) +
  geom_point(aes(colour = DE, alpha = DE, size = DE)) +
  geom_text_repel(
    aes(label = gene_name),
    subset(ggdata, Curated), min.segment.length = unit(0,"lines")) +
  scale_colour_manual(values = sig_colors) +
  scale_alpha_manual(values = sig_alpha) +
  scale_size_manual(values = sig_size) +
  scale_y_continuous(limits = axes_range) +
  scale_x_continuous(limits = axes_range) +
  labs(
    title = "6h", subtitle = "STM-D23580 / STM-LT2",
    y = "STM-D23580", x = "STM-LT2"
  ) +
  guides(colour="none", size="none", alpha="none") +
  coord_fixed() +
  theme_bw() +
  theme(panel.grid.minor = element_blank()); gg
ggsave(file.path(outdir, "mean_6h_infected_label_curated.pdf"), gg, height=5, width=6.5)
```
