---
title: "Heat map of genes of interest"
author: "Kevin Rue-Albrecht"
date: "27/01/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
stopifnot(
  require(scater),
  require(scran),
  require(ggplot2),
  require(SummarizedExperiment),
  require(RColorBrewer),
  require(circlize),
  require(ComplexHeatmap)
)
sce.norm <- readRDS("rds/sce.norm.rds")
sce.norm <- sce.norm[,order(sce.norm$Group)]
sce.endo <- sce.norm[!isSpike(sce.norm, "ERCC"),]
col.time <- brewer.pal(9, "Set3")[c(2,7:8)]
col.infection <- brewer.pal(12, "Paired")[c(9,4,2)]
col.status <- brewer.pal(12, "Paired")[c(9,1,7)]
names(col.time) <- levels(sce.endo$Time)[1:3]
names(col.infection) <- levels(sce.endo$Infection)
names(col.status) <- levels(sce.endo$Status)
outdir <- "_011_heatmap_out"; dir.create(outdir, showWarnings = FALSE)
```

# Color maps

## Colors

```{r exprsRange_all}
exprsRange_all <- range(assay(sce.endo, "logcounts"))
colorMap <- circlize::colorRamp2(
  c(min(exprsRange_all), median(exprsRange_all), max(exprsRange_all)),
  c("blue","white","red"))
```

# Heat map

## Subset to genes

```{r}
geneNames <- c("CD1A", "APOE")
geneIds <- with(rowData(sce.endo), gene_id[match(geneNames, gene_name)])
sce.genes <- sce.endo[geneIds,]
```

## Refine colour map for expression 

```{r exprsRange}
exprsRange <- range(assay(sce.genes, "logcounts")) * 1.25
colorMap <- circlize::colorRamp2(
  c(min(exprsRange), median(exprsRange), max(exprsRange)),
  c("blue","white","red"))
```

## Subset by Treatment

```{r subset_treatment}
sce.mock <- sce.genes[,sce.genes$Infection == "Mock"]
mat.mock <- assay(sce.mock, "logcounts")
sce.d23inf <- sce.genes[,sce.genes$Treatment == "STM-D23580_Infected"]
mat.d23inf <- assay(sce.d23inf, "logcounts")
sce.d23exp <- sce.genes[,sce.genes$Treatment == "STM-D23580_Exposed"]
mat.d23exp <- assay(sce.d23exp, "logcounts")
sce.lt2inf <- sce.genes[,sce.genes$Treatment == "STM-LT2_Infected"]
mat.lt2inf <- assay(sce.lt2inf, "logcounts")
sce.lt2exp <- sce.genes[,sce.genes$Treatment == "STM-LT2_Exposed"]
mat.lt2exp <- assay(sce.lt2exp, "logcounts")
```

Set `rownames` for the last panels of the heat map:

```{r rownames_ht}
rownames(mat.lt2exp) <- geneNames
```

## Assemble the heat map

```{r HeatmapList}
ht <- HeatmapList(
  Heatmap(
    matrix = mat.mock, col = colorMap,
    column_title = "Mock\nUninfected",
    show_row_names = FALSE, show_column_names = FALSE,
    cluster_rows = FALSE,
    show_heatmap_legend = FALSE) +
    Heatmap(
      matrix = mat.d23inf, col = colorMap,
      column_title = "STM-D23580\nInfected",
      show_row_names = FALSE, show_column_names = FALSE,
      show_heatmap_legend = FALSE) +
    Heatmap(
      matrix = mat.d23exp, col = colorMap,
      column_title = "STM-D23580\nExposed",
      show_row_names = FALSE, show_column_names = FALSE,
      show_heatmap_legend = FALSE) +
    Heatmap(
      matrix = mat.lt2inf, col = colorMap,
      column_title = "STM-LT2\nInfected",
      show_row_names = FALSE, show_column_names = FALSE,
      show_heatmap_legend = FALSE) +
    Heatmap(
      matrix = mat.lt2exp, col = colorMap,
      name = "norm.\nexpr.",
      column_title = "STM-LT2\nExposed",
      show_column_names = FALSE)
)
```

```{r draw}
draw(ht)
```

```{r}
pdf(file.path(outdir, "heatmap_treatment_CD1A_APOE.pdf"), height = 2, width = 8)
draw(ht)
dev.off()
```

