
---
title: "Bonus"
bibliography:
  bibtex.bib
---

Enjoy a few by-products of this analysis!

# Songs

## Single-cell

Guided by the flow

Into separate wells

> Down the tube they go / 
> Lysed by the buffer /
> (change)

-- --

*Oh, single cells, single cells,*

*Single in their well*

*Oh, what fun it is to yield*

*So little RNA, hey!*

*Oh, single cells, single cells,*

*Single all the way*

*Oh, what fun it is to sort*

*'Em in all those different wells!*

-- --


## Wake me up when sequencing ends

Summer has come and passed
The innocent can never last
Wake me up when September ends

Like my father's come to pass
Seven years has gone so fast
Wake me up when September ends

Here comes the rain again
Falling from the stars
Drenched in my pain again
Becoming who we are

As my memory rests
But never forgets what I lost
Wake me up when September ends

Summer has come and passed
The innocent can never last
Wake me up when September ends

Ring out the bells again
Like we did when spring began
Wake me up when September ends

Here comes the rain again
Falling from the stars
Drenched in my pain again
Becoming who we are

As my memory rests
But never forgets what I lost
Wake me up when September ends

Summer has come and passed
The innocent can never last
Wake me up when September ends

Like my father's come to pass
Twenty years has gone so fast
Wake me up when September ends
Wake me up when September ends
Wake me up when September ends
