---
title: "Normalised gene expression"
author: "Kevin Rue-Albrecht"
date: "20/04/2017"
output: html_document
---

<!-- As HTML pages are built independently, large objects need to be
reimported from disk, and smaller ones quickly recomputed. -->

```{r setup, include=FALSE}
library(scater)
library(ggplot2)
sce.endo <- readRDS("rds/13_sce.endo_clusters.rds")
```

# Prepare data

Let us create for each cell, a new `phenoData` field that indicates which
clustes of which time point it belongs to:

```{r}
qc.time <- NA
qc.time[sce.endo$Time == "2h"] <- 
  paste("2h", sce.endo$quickCluster.2h[sce.endo$Time == "2h"])
qc.time[sce.endo$Time == "4h"] <-
  sprintf("4h %s", sce.endo$quickCluster.4h[sce.endo$Time == "4h"])
qc.time[sce.endo$Time == "6h"] <-
  sprintf("6h %s", sce.endo$quickCluster.6h[sce.endo$Time == "6h"])
qc.time <- factor(qc.time, c(
  paste("2h", levels(sce.endo$quickCluster.2h)),
  paste("4h", levels(sce.endo$quickCluster.4h)),
  paste("6h", levels(sce.endo$quickCluster.6h))
))
sce.endo$quickCluster.time <- qc.time
```

# normExprsByName {.tabset}

## Basic

```{r normExprsByName.basic}
normExprsByName.basic <- function(geneName = 'RAB29'){
  geneId <-
    subset(fData(sce.endo), gene_name == geneName, "gene_id", drop = TRUE)
  stopifnot(length(geneId) == 1)
  gdata <- data.frame(
    norm_exprs = norm_exprs(sce.endo)[geneId,],
    pData(sce.endo)[,c("Infection","Status","Time","quickCluster.time")],
    row.names = sampleNames(sce.endo)
  )
  ggplot(gdata, aes(Infection, norm_exprs)) + 
    geom_violin() +
    geom_jitter(, width = 0.1) +
    facet_grid(Time ~ Status) +
    ggtitle(sprintf("%s - %s", geneName, geneId))
}
```

## Colour:Cluster

```{r normExprsByName}
normExprsByName <- function(geneName = 'RAB29'){
  geneId <-
    subset(fData(sce.endo), gene_name == geneName, "gene_id", drop = TRUE)
  stopifnot(length(geneId) == 1)
  gdata <- data.frame(
    norm_exprs = norm_exprs(sce.endo)[geneId,],
    pData(sce.endo)[,c("Infection","Status","Time","quickCluster.time")],
    row.names = sampleNames(sce.endo)
  )
  ggplot(gdata, aes(Infection, norm_exprs)) + 
    geom_violin() +
    geom_jitter(aes(colour = quickCluster.time), width = 0.1) +
    facet_grid(Time ~ Status) +
    ggtitle(sprintf("%s - %s", geneName, geneId))
}
```

# RAB29

```{r RAB29}
normExprsByName()
```

# MGLL

```{r MGLL}
normExprsByName("MGLL")
```

# NLRP1

```{r NLRP1}
normExprsByName("NLRP1")
```

# CTSB

```{r CTSB}
normExprsByName("CTSB")
```

# IL6

```{r IL6}
normExprsByName("IL6")
```

# CD86

```{r CD86}
genename <- "CD86"
normExprsByName.basic(genename) + theme_minimal()
ggsave(sprintf("20170525_lab-meeting/%s.pdf", genename), width = 5, height = 5)
```

# CD83

```{r CD83}
genename <- "CD83"
normExprsByName.basic(genename) + theme_minimal()
ggsave(sprintf("20170525_lab-meeting/%s.pdf", genename), width = 5, height = 5)
```

# HLA-DR {.tabset}

## HLA-DRA

```{r}
genename <- "HLA-DRA"
normExprsByName.basic(genename) + theme_minimal()
ggsave(sprintf("20170525_lab-meeting/%s.pdf", genename), width = 5, height = 5)
```

## HLA-DRB1

```{r}
genename <- "HLA-DRB1"
normExprsByName.basic(genename) + theme_minimal()
ggsave(sprintf("20170525_lab-meeting/%s.pdf", genename), width = 5, height = 5)
```

## HLA-DRB5

```{r}
genename <- "HLA-DRB5"
normExprsByName.basic(genename) + theme_minimal()
ggsave(sprintf("20170525_lab-meeting/%s.pdf", genename), width = 5, height = 5)
```

## HLA-DRB6

```{r}
genename <- "HLA-DRB6"
normExprsByName.basic(genename) + theme_minimal()
ggsave(sprintf("20170525_lab-meeting/%s.pdf", genename), width = 5, height = 5)
```

# IL10

```{r IL10}
genename <- "IL10"
normExprsByName.basic(genename) + theme_minimal()
ggsave(sprintf("20170525_lab-meeting/%s.pdf", genename), width = 5, height = 5)
```
